# Generated by Django 4.2.4 on 2023-09-18 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Уникальный ID бренда')),
                ('name', models.CharField(max_length=4000, verbose_name='Бренд')),
                ('description', models.CharField(blank=True, max_length=240, null=True, verbose_name='Описание')),
                ('place', models.IntegerField(blank=True, null=True, verbose_name='Место в списке')),
                ('brand_image', models.ImageField(blank=True, null=True, upload_to='images/brand', verbose_name='Изображение')),
                ('brand_banner', models.ImageField(blank=True, null=True, upload_to='images/brand', verbose_name='Баннер')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['place'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Уникальный ID каждой группы')),
                ('name', models.CharField(max_length=4000, verbose_name='Имя группы')),
                ('description', models.CharField(blank=True, max_length=4000, null=True, verbose_name='Описание')),
                ('place', models.IntegerField(blank=True, null=True, verbose_name='Место в списке')),
                ('group_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand', verbose_name='ID Бренда,                                                                                     к которому относится группа')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['place'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Уникальный ID бренда')),
                ('name', models.CharField(max_length=4000, verbose_name='Бренд')),
                ('description', models.CharField(blank=True, max_length=4000, null=True, verbose_name='Описание')),
                ('unit_image', models.ImageField(blank=True, null=True, upload_to='images/unit', verbose_name='Изображение')),
                ('place', models.IntegerField(blank=True, null=True, verbose_name='Место в списке')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'ordering': ['place'],
            },
        ),
        migrations.CreateModel(
            name='UnitToCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Уникальный ID каждой связи направления и группы')),
                ('group', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.group', verbose_name='Уникальный ID группы,                                                                                         принадлежащей направлению')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.unit', verbose_name='Уникальный ID направления')),
            ],
            options={
                'verbose_name': 'Связь группы и направления',
                'verbose_name_plural': 'Связь групп и направлений',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Уникальный ID каждого товара')),
                ('ref', models.CharField(max_length=4000, verbose_name='Код товара')),
                ('name', models.CharField(max_length=4000, verbose_name='Имя товара')),
                ('place', models.IntegerField(blank=True, null=True, verbose_name='Место в списке')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.group', verbose_name='Уникальный ID группы,                                                                                     к которой принадлежит товар')),
            ],
            options={
                'verbose_name': 'Связь продукта и его группы',
                'verbose_name_plural': 'Связь продуктов и их групп',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryToGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Уникальный ID каждой связи групп между собой')),
                ('final', models.BooleanField(default=False, verbose_name='Отметка о том, что это группа последняя в категории                                                             и при переходе в группу будут отображаться уже товары')),
                ('group', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descendant', to='catalog.group', verbose_name='ID группы')),
                ('parent_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ancestor', to='catalog.group', verbose_name='ID группы-родителя. Если указать 0, то группа будет отображаться                                         как начальная в категории Бренда')),
            ],
            options={
                'verbose_name': 'Связь группы и её родителя',
                'verbose_name_plural': 'Связь групп и их родителей',
                'ordering': ['id'],
            },
        ),
    ]
