# Generated by Django 4.2.4 on 2023-08-29 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('name', models.CharField(max_length=240, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=240)),
                ('place', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['place'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=240, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=240, null=True)),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.brand')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=240, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=240, null=True)),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('name', models.CharField(max_length=240, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=240)),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Typeclass',
            fields=[
                ('name', models.CharField(max_length=240, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=240, null=True)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=240)),
                ('description', models.CharField(max_length=240)),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.group')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['ref'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.typeclass'),
        ),
        migrations.AddField(
            model_name='category',
            name='unit_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.unit'),
        ),
    ]
