# Generated by Django 4.2.4 on 2023-09-17 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='image',
            new_name='unit_image',
        ),
    ]
