# Generated by Django 4.2.4 on 2023-09-16 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_unittocategory_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttogroup',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.group', verbose_name='Уникальный ID группы,                                                                                     к которой принадлежит товар'),
        ),
    ]
