# Generated by Django 4.2.4 on 2023-10-29 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_brand_description_alter_group_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytogroup',
            name='group_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand', verbose_name='ID Бренда,                                                                                     к которому относится группа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ancestor_for_product', to='catalog.group', verbose_name='Уникальный ID группы, к которой принадлежит товар'),
        ),
    ]
