# Generated by Django 4.2.4 on 2023-10-29 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_categorytogroup_group_brand_alter_product_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittocategory',
            name='group_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand', verbose_name='ID Бренда,                                                                                         к которому относится группа'),
        ),
    ]
