# Generated by Django 4.2.4 on 2023-09-17 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_unittocategory_group_alter_unittocategory_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unittocategory',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.group', verbose_name='Уникальный ID группы,                                                                                         принадлежащей направлению'),
        ),
        migrations.AlterField(
            model_name='unittocategory',
            name='unit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.unit', verbose_name='Уникальный ID направления'),
        ),
    ]
