# Generated by Django 4.2.4 on 2023-11-05 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_unittocategory_group_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_banner',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/images/banner', verbose_name='Баннер'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/images/image', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/images/image', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_banner',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/images/banner', verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/images/image', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand', verbose_name='ID Бренда, к которому относится группа'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/images/image', verbose_name='Изображение'),
        ),
    ]
