# Generated by Django 4.2.4 on 2023-09-17 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_unittocategory_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytogroup',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descendant', to='catalog.group', verbose_name='ID группы'),
        ),
        migrations.AlterField(
            model_name='categorytogroup',
            name='parent_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ancestor', to='catalog.group', verbose_name='ID группы-родителя. Если указать 0, то группа будет отображаться                                         как начальная в категории Бренда'),
        ),
    ]
