# Generated by Django 4.2.4 on 2023-09-17 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_categorytogroup_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytogroup',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descendant', to='catalog.group', verbose_name='ID группы'),
        ),
        migrations.AlterField(
            model_name='producttogroup',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.group', verbose_name='Уникальный ID группы,                                                                                     к которой принадлежит товар'),
        ),
        migrations.AlterField(
            model_name='unittocategory',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.group', verbose_name='Уникальный ID группы,                                                                                         принадлежащей направлению'),
        ),
    ]
