# Generated by Django 4.2.4 on 2023-09-16 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesToProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Уникальный ID связи товара и его файлов')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='images/product', verbose_name='Изображение')),
                ('product_tech_description', models.FileField(blank=True, null=True, upload_to='files/tech_description', verbose_name='Описание товара')),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='Уникальный ID каждого товара')),
            ],
            options={
                'verbose_name': 'Связь товара и его файлов',
                'verbose_name_plural': 'Связи товаров и их файлов',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FilesToGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Уникальный ID связи группы и её файлов')),
                ('group_image', models.ImageField(blank=True, null=True, upload_to='images/group', verbose_name='Изображение')),
                ('group_banner', models.ImageField(blank=True, null=True, upload_to='images/group', verbose_name='Баннер')),
                ('group_registration', models.FileField(blank=True, null=True, upload_to='files/registration', verbose_name='РУ')),
                ('group_instruction', models.FileField(blank=True, null=True, upload_to='files/registration', verbose_name='Инструкция')),
                ('group', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.group', verbose_name='Уникальный ID каждой группы')),
            ],
            options={
                'verbose_name': 'Связь группы и её файлов',
                'verbose_name_plural': 'Связи групп и их файлов',
                'ordering': ['id'],
            },
        ),
    ]
