# Generated by Django 4.2.4 on 2023-08-29 19:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_organization', models.CharField(max_length=240, verbose_name='Название организации')),
                ('customer_name', models.CharField(max_length=240, verbose_name='Ваше имя')),
                ('customer_phone', models.CharField(max_length=240, verbose_name='Номер телефона')),
                ('customer_email', models.CharField(max_length=240, verbose_name='Email')),
                ('customer_comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('order_date', models.DateTimeField(auto_now=True, verbose_name='Дата запроса')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Строка запроса',
                'verbose_name_plural': 'Строки запроса',
            },
        ),
    ]
